sudo: true

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql
  
matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=4.9
    - php: 7.2
      env: WP_TRAVISCI=phpcs
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.3
      env: WP_VERSION=latest

before_script:
  - mkdir -p build/logs
  - chmod +x script/*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - script/setup

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      script/cibuild-phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      script/cibuild-phpcs
    fi
